### ISSUE TITLE
tar --transform not working on Mac

### ISSUE THREAD

**Issue by BeachBum24-7** [Psy-Fer/fast5_fetcher#4]
When I tried to run the fast5_fetcher.py script, the terminal returned the following error: 
tar: Option --transform=s/.*\/// is not supported

My assumption was that the tar command on Mac has no "--transform" option (contrary to tar in a linux environment).

I fixed it by installing "gnu-tar" via homebrew and replaced 'tar' with 'gtar' in line 324 of the fast5_fetcher.py script.

**Comment by Psy-Fer** [comment]
Ahh great!
I'll apply a fix, and add in a requirement for MacOS.
Thanks for that :)

**Comment by Psy-Fer** [comment]
Fixed with version 1.1.1

Install gnu-tar with homebrew, and fast5_fetcher will detect your OS and use it.

Thanks Kai.
